### ISSUE TITLE
Issue on oandamomentumv20.ipynb In [2]:

### ISSUE THREAD

**Issue by alexismanalo** [benjaminchodroff/oandamomentum#1]
I'm getting the error below using a Jupyter notebook:

> 
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-5-75a5ab6ef09e> in <module>()
>       5 
>       6 # The v20 api handles from times a little differently - be careful of the timezone
> ----> 7 params={"from": parser.parse("2016-12-07 18:00:00 EDT").strftime('%s'),
>       8         "to": parser.parse("2016-12-10 00:000:00 EDT").strftime('%s'),
>       9         "granularity":'M1',
> 
> ValueError: Invalid format string

```
import pandas as pd
import datetime
from dateutil import parser
import oandapyV20.endpoints.instruments as instruments

# The v20 api handles from times a little differently - be careful of the timezone
params={"from": parser.parse("2016-12-07 18:00:00 EDT").strftime('%s'),
        "to": parser.parse("2016-12-10 00:000:00 EDT").strftime('%s'),
        "granularity":'M1',
        "price":'A'}
r = instruments.InstrumentsCandles(instrument="EUR_USD",params=params)
data = client.request(r)
results= [{"time":x['time'],"closeAsk":float(x['ask']['c'])} for x in data['candles']]
df = pd.DataFrame(results).set_index('time')

df.index = pd.DatetimeIndex(df.index)

df.info()
```

**Comment by benjaminchodroff** [comment]
I tested this notebook on a Mac. However, it appears python's strftime works slightly differently on Windows. This may be related to your issue? https://stackoverflow.com/questions/11743019/convert-python-datetime-to-epoch-with-strftime

From the article:
If you want to convert a python datetime to seconds since epoch you should do it explicitly:
>>> datetime.datetime(2012,04,01,0,0).strftime('%s')
'1333234800'
>>> (datetime.datetime(2012,04,01,0,0) - datetime.datetime(1970,1,1)).total_seconds()
1333238400.0

Please replace line 7 and 8 with this approach, and see if that works?

**Comment by alexismanalo** [comment]
Thanks! I figured that there was no need to parse the date. The revised code should be this:

```
import pandas as pd
import datetime
from dateutil import parser
import oandapyV20.endpoints.instruments as instruments

# The v20 api handles from times a little differently - be careful of the timezone
params={"from": '2016-12-07T18:00:00Z',
        "to": '2016-12-10T00:00:00Z',
        "granularity":'M1',
        "price":'A'}
r = instruments.InstrumentsCandles(instrument="EUR_USD",params=params)
data = client.request(r)
results= [{"time":x['time'],"closeAsk":float(x['ask']['c'])} for x in data['candles']]
df = pd.DataFrame(results).set_index('time')

df.index = pd.DatetimeIndex(df.index)

df.info()
```

With date and time in RFC3339 format. I just got stuck again in another line. LOL

Let me debug and will post another issue if need be.
